# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

pool:
  vmImage: "ubuntu-latest"
strategy:
  matrix:
    Python36:
      python.version: "3.6"
    Python37:
      python.version: "3.7"
    Python38:
      python.version: "3.8"

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "$(python.version)"
    displayName: "Use Python $(python.version)"

  - script: |
      sudo apt-get update && sudo apt-get install python3-venv
    condition: startswith(variables['python.version'], '3')
    displayName: "install deps"

  - script: |
      make lint
    displayName: "lint"

  - script: |
      make test
    displayName: "test"

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: "Cobertura"
      summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/.coverage.xml"

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: "$(System.DefaultWorkingDirectory)/**/.pytest.xml"
